In [1]:
import pandas as pd
df1 = pd.read_csv("./ant-learn-python/5分钟学会Python爬取天气数据/beijing_tianqi_2018.csv")

In [2]:
df1

            ymd bWendu yWendu tianqi fengxiang fengli  aqi aqiInfo  aqiLevel
0    2018-01-01     3℃    -6℃   晴~多云       东北风   1-2级   59       良         2
1    2018-01-02     2℃    -5℃   阴~多云       东北风   1-2级   49       优         1
2    2018-01-03     2℃    -5℃     多云        北风   1-2级   28       优         1
3    2018-01-04     0℃    -8℃      阴       东北风   1-2级   28       优         1
4    2018-01-05     3℃    -6℃   多云~晴       西北风   1-2级   50       优         1
..          ...    ...    ...    ...       ...    ...  ...     ...       ...
360  2018-12-27    -5℃   -12℃   多云~晴       西北风     3级   48       优         1
361  2018-12-28    -3℃   -11℃      晴       西北风     3级   40       优         1
362  2018-12-29    -3℃   -12℃      晴       西北风     2级   29       优         1
363  2018-12-30    -2℃   -11℃   晴~多云       东北风     1级   31       优         1
364  2018-12-31    -2℃   -10℃     多云       东北风     1级   56       良         2

[365 rows x 9 columns]

In [27]:
df1['bWendu']=df1['bWendu'].astype(str).str.replace("℃","").astype('int32')

In [32]:
df1['yWendu']=df1['yWendu'].astype(str).str.replace("℃","").astype('int32')

In [25]:
df1['ymd']=df1['ymd'].astype(str)
print(df1['ymd'].dtypes)

object

In [33]:
df1.dtypes

ymd          object
bWendu        int32
yWendu        int32
tianqi       object
fengxiang    object
fengli       object
aqi           int64
aqiInfo      object
aqiLevel      int64
dtype: object

In [36]:
df1.describe()

           bWendu      yWendu         aqi    aqiLevel
count  365.000000  365.000000  365.000000  365.000000
mean    18.665753    8.358904   82.183562    2.090411
std     11.858046   11.755053   51.936159    1.029798
min     -5.000000  -12.000000   21.000000    1.000000
25%      8.000000   -3.000000   46.000000    1.000000
50%     21.000000    8.000000   69.000000    2.000000
75%     29.000000   19.000000  104.000000    3.000000
max     38.000000   27.000000  387.000000    6.000000